version: 2

sources:
  - name: order_service
    database: <ORDER_SERVICE_DB>
    schema: <ORDER_SERVICE_SCHEMA>
    tables:
      - name: orders
      - name: order_items
      - name: order_status_history
      - name: products

  - name: user_service
    database: <USER_SERVICE_DB>
    schema: <USER_SERVICE_SCHEMA>
    tables:
      - name: users
      - name: user_addresses
      - name: user_status_history

  - name: logistics_service
    database: <LOGISTICS_SERVICE_DB>
    schema: <LOGISTICS_SERVICE_SCHEMA>
    tables:
      - name: shipments
      - name: shipment_movements
      - name: shipment_status_history
      - name: warehouses
      - name: pickup_points
